In [ ]:
# This file is a single TensorDecisionTreeRegressorP.py model grown on 818 samples without slicing

import os
import nibabel as nib
import numpy as np
import matplotlib as plt
import pandas as pd
from sklearn.model_selection import train_test_split

# File path to the CSV file
csv_file = '/Users/zc56/Documents/CommenDesktop/RICE/MyProject/Bayes_Tensor_Tree/3D-images/ADNIData.csv'
#csv_file = '/home/zc56/Bayes_Tensor_Tree/3D-images/ADNIData.csv'
# Load the CSV file into a pandas DataFrame
df = pd.read_csv(csv_file)

# Extract the 'ADAS11' column as the y variable
y_variable = df['ADAS11'].values  # Convert to NumPy array if needed

# Print the shape and first few values of the y variable
print(f"y variable shape: {y_variable.shape}")
print(f"First 5 values of y variable: {y_variable[:5]}")





directory = '/Users/zc56/Documents/CommenDesktop/RICE/MyProject/Bayes_Tensor_Tree/3D-images/3D-Images/bl'
#directory = '/home/zc56/Bayes_Tensor_Tree/3D-images/3D-Images/bl'
# Initialize a list to hold 3D images
image_list = []

# Loop over all files in the directory
for filename in os.listdir(directory):
    if filename.endswith('.nii.gz'):
        file_path = os.path.join(directory, filename)
        
        # Load the NIfTI file
        img = nib.load(file_path)
        
        # Get the data as a NumPy array
        data = img.get_fdata()
        
        # Append the 3D image data to the list
        image_list.append(data)
        
        # Print the filename and data shape
        #print(f"Loaded {filename}, shape: {data.shape}")

# Stack the 3D images along a new axis to create a 4D tensor
if image_list:
    image_tensor = np.stack(image_list, axis=0)
    print(f"Stacked 4D tensor shape: {image_tensor.shape}")
else:
    print("No images loaded.")



X_train, X_test, y_train, y_test = train_test_split(image_tensor, y_variable, test_size=0.2, random_state=42)

# Print the shapes of the training and testing data
print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_test shape: {y_test.shape}")








import numpy as np
from concurrent.futures import ProcessPoolExecutor
import time
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
import tensorly as tl

#Debugging import
import importlib
var = 'TensorDecisionTreeRegressorP' #the published version of code
package = importlib.import_module(var)
for name, value in package.__dict__.items():
    if not name.startswith("__"):
        globals()[name] = value


from TensorDecisionTreeRegressorP import *



start_time = time.time()

model = TensorDecisionTreeRegressor(
    max_depth=3,
    min_samples_split=2,
    split_method='variance_LS',
    split_rank=2,
    CP_reg_rank=3,
    Tucker_reg_rank=3,
    n_mode=3
)
model.sample_rate = 0.05
model.use_mean_as_threshold = False
model.fit(X_train, y_train)

#model.prune(X_val=None, y_val=None, model_type='cp', alpha=0.)
predictions = model.predict(X_test)
res = mean_squared_error(predictions, y_test) / np.var(y_test)

end_time = time.time()
computation_time = end_time - start_time

print("relative squared error: ", res)
print("computation time: ", computation_time)



y variable shape: (818,)
First 5 values of y variable: [ 3.    3.33  6.   19.33  3.67]
Stacked 4D tensor shape: (818, 48, 48, 48)
X_train shape: (654, 48, 48, 48)
y_train shape: (654,)
X_test shape: (164, 48, 48, 48)
y_test shape: (164,)


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3787: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/core/_methods.py:163: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean,
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/core/_methods.py:198: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


None-->X (654, 48, 48) [[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ...

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tensorly/regression/cp_regression.py:116: RuntimeWarning: invalid value encountered in scalar divide
  weight_evolution = abs(norm_W[-1] - norm_W[-2]) / norm_W[-1]
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tensorly/regression/tucker_regression.py:126: RuntimeWarning: invalid value encountered in scalar divide
  weight_evolution = abs(norm_W[-1] - norm_W[-2]) / norm_W[-1]


KeyboardInterrupt: 