In [101]:
# sliced 3D real image
import warnings
warnings.filterwarnings("ignore")


import numpy as np
from concurrent.futures import ProcessPoolExecutor
import time
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
import tensorly as tl

#Debugging import
import importlib
var = 'TensorDecisionTreeRegressorP' #the published version of code
package = importlib.import_module(var)
for name, value in package.__dict__.items():
    if not name.startswith("__"):
        globals()[name] = value

from TensorDecisionTreeRegressorP import *

import os
import nibabel as nib
import numpy as np
import matplotlib as plt
import pandas as pd
from sklearn.model_selection import train_test_split

# File path to the CSV file
csv_file = '/Users/zc56/Documents/CommenDesktop/RICE/MyProject/Bayes_Tensor_Tree/3D-images/ADNIData.csv'
#csv_file = '/home/zc56/Bayes_Tensor_Tree/3D-images/ADNIData.csv'
# Load the CSV file into a pandas DataFrame
df = pd.read_csv(csv_file)

# Extract the 'ADAS11' column as the y variable
y_variable = df['ADAS11'].values  # Convert to NumPy array if needed

# Print the shape and first few values of the y variable
print(f"y variable shape: {y_variable.shape}")
print(f"First 5 values of y variable: {y_variable[:5]}")





directory = '/Users/zc56/Documents/CommenDesktop/RICE/MyProject/Bayes_Tensor_Tree/3D-images/3D-Images/bl'
#directory = '/home/zc56/Bayes_Tensor_Tree/3D-images/3D-Images/bl'
# Initialize a list to hold 3D images
# Initialize a list to hold 3D images
image_list = []

# Loop over all files in the directory
for filename in os.listdir(directory):
    if filename.endswith('.nii.gz'):
        file_path = os.path.join(directory, filename)
        
        # Load the NIfTI file
        img = nib.load(file_path)
        
        # Get the data as a NumPy array
        data = img.get_fdata()
        
        # Append the 3D image data to the list
        image_list.append(data)
        
        # Print the filename and data shape
        #print(f"Loaded {filename}, shape: {data.shape}")

# Stack the 3D images along a new axis to create a 4D tensor
if image_list:
    image_tensor = np.stack(image_list, axis=0)
    #print(f"Stacked 4D tensor shape: {image_tensor.shape}")
else:
    print("No images loaded.")


X_train, X_test, y_train, y_test = train_test_split(image_tensor, y_variable, test_size=0.2, random_state=42)
y_train = np.nan_to_num(y_train, nan=0.0)
# Print the shapes of the training and testing data
print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_test shape: {y_test.shape}")


start_time = time.time()
model_list = list()  
pred_list = list()
RSE_list = list()

sl = X_train[:, :, :, 1:3]  
model = TensorDecisionTreeRegressor( 
    max_depth=3, 
    min_samples_split=20, 
    split_method='variance', 
    split_rank=3,
    n_mode = 3)   
model.sample_rate = 1
model.fit(sl, y_train)
#model.prune(X_val=None, y_val=None, model_type='mean')
predictions = model.predict(X_train[:, :, :, 1:3])
res = mean_squared_error(predictions, y_train)/np.var(y_train)

end_time = time.time()
print(res)
print(f"computation time : ", end_time - start_time)
#print(f"predictions with {s} samples: ", pred_list)
print(f"RSE with : ", mean_squared_error(np.mean(np.array(pred_list), axis = 0), y_train)/np.var(y_train))

y variable shape: (818,)
First 5 values of y variable: [ 3.    3.33  6.   19.33  3.67]
X_train shape: (654, 48, 48, 48)
y_train shape: (654,)
X_test shape: (164, 48, 48, 48)
y_test shape: (164,)
0.9434788884533254
computation time :  254.7278552055359


InvalidParameterError: The 'y_true' parameter of mean_squared_error must be an array-like. Got nan instead.

In [104]:
# sliced 3D real image
import warnings
warnings.filterwarnings("ignore")


import numpy as np
from concurrent.futures import ProcessPoolExecutor
import time
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
import tensorly as tl

#Debugging import
import importlib
var = 'TensorDecisionTreeRegressorP' #the published version of code
package = importlib.import_module(var)
for name, value in package.__dict__.items():
    if not name.startswith("__"):
        globals()[name] = value

from TensorDecisionTreeRegressorP import *

import os
import nibabel as nib
import numpy as np
import matplotlib as plt
import pandas as pd
from sklearn.model_selection import train_test_split

# File path to the CSV file
csv_file = '/Users/zc56/Documents/CommenDesktop/RICE/MyProject/Bayes_Tensor_Tree/3D-images/ADNIData.csv'
#csv_file = '/home/zc56/Bayes_Tensor_Tree/3D-images/ADNIData.csv'
# Load the CSV file into a pandas DataFrame
df = pd.read_csv(csv_file)

# Extract the 'ADAS11' column as the y variable
y_variable = df['ADAS11'].values  # Convert to NumPy array if needed

# Print the shape and first few values of the y variable
print(f"y variable shape: {y_variable.shape}")
print(f"First 5 values of y variable: {y_variable[:5]}")





directory = '/Users/zc56/Documents/CommenDesktop/RICE/MyProject/Bayes_Tensor_Tree/3D-images/3D-Images/bl'
#directory = '/home/zc56/Bayes_Tensor_Tree/3D-images/3D-Images/bl'
# Initialize a list to hold 3D images
# Initialize a list to hold 3D images
image_list = []

# Loop over all files in the directory
for filename in os.listdir(directory):
    if filename.endswith('.nii.gz'):
        file_path = os.path.join(directory, filename)
        
        # Load the NIfTI file
        img = nib.load(file_path)
        
        # Get the data as a NumPy array
        data = img.get_fdata()
        
        # Append the 3D image data to the list
        image_list.append(data)
        
        # Print the filename and data shape
        #print(f"Loaded {filename}, shape: {data.shape}")

# Stack the 3D images along a new axis to create a 4D tensor
if image_list:
    image_tensor = np.stack(image_list, axis=0)
    #print(f"Stacked 4D tensor shape: {image_tensor.shape}")
else:
    print("No images loaded.")


X_train, X_test, y_train, y_test = train_test_split(image_tensor, y_variable, test_size=0.2, random_state=42)
y_train = np.nan_to_num(y_train, nan=0.0)
# Print the shapes of the training and testing data
print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_test shape: {y_test.shape}")


start_time = time.time()
model_list = list()  
pred_list = list()
RSE_list = list()
for i in range(2, X_train.shape[3]-2):
    sl = X_train[:, :, :, i]  
    model = TensorDecisionTreeRegressor( 
        max_depth=3, 
        min_samples_split=20, 
        split_method='lowrank_reg', 
        split_rank=3,
        n_mode = 3,
        CP_reg_rank=3,
        )   
    model.sample_rate = 1
    model.fit(sl, y_train)

    #model.prune(X_val=None, y_val=None, model_type='mean')
    predictions = model.predict(X_test[:, :, :, i], regression_method="cp")

    res = mean_squared_error(predictions, y_test)/np.var(y_test)
    pred_list.append(predictions)
    model_list.append(model)
    RSE_list.append(res)

    end_time = time.time()
    print(res)
print(f"computation time : ", end_time - start_time)
#print(f"predictions with {s} samples: ", pred_list)
print(f"RSE with : ", mean_squared_error(np.mean(np.array(pred_list), axis = 0), y_test)/np.var(y_test))

y variable shape: (818,)
First 5 values of y variable: [ 3.    3.33  6.   19.33  3.67]
X_train shape: (654, 48, 48, 48)
y_train shape: (654,)
X_test shape: (164, 48, 48, 48)
y_test shape: (164,)


KeyboardInterrupt: 

In [38]:
# sliced 3D real image
import warnings
warnings.filterwarnings("ignore")


import numpy as np
from concurrent.futures import ProcessPoolExecutor
import time
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
import tensorly as tl

#Debugging import
import importlib
var = 'TensorDecisionTreeRegressorP' #the published version of code
package = importlib.import_module(var)
for name, value in package.__dict__.items():
    if not name.startswith("__"):
        globals()[name] = value

from TensorDecisionTreeRegressorP import *

import os
import nibabel as nib
import numpy as np
import matplotlib as plt
import pandas as pd
from sklearn.model_selection import train_test_split

# File path to the CSV file
csv_file = '/Users/zc56/Documents/CommenDesktop/RICE/MyProject/Bayes_Tensor_Tree/3D-images/ADNIData.csv'
#csv_file = '/home/zc56/Bayes_Tensor_Tree/3D-images/ADNIData.csv'
# Load the CSV file into a pandas DataFrame
df = pd.read_csv(csv_file)

# Extract the 'ADAS11' column as the y variable
y_variable = df['ADAS11'].values  # Convert to NumPy array if needed

# Print the shape and first few values of the y variable
print(f"y variable shape: {y_variable.shape}")
print(f"First 5 values of y variable: {y_variable[:5]}")





directory = '/Users/zc56/Documents/CommenDesktop/RICE/MyProject/Bayes_Tensor_Tree/3D-images/3D-Images/bl'
#directory = '/home/zc56/Bayes_Tensor_Tree/3D-images/3D-Images/bl'
# Initialize a list to hold 3D images
# Initialize a list to hold 3D images
image_list = []

# Loop over all files in the directory
for filename in os.listdir(directory):
    if filename.endswith('.nii.gz'):
        file_path = os.path.join(directory, filename)
        
        # Load the NIfTI file
        img = nib.load(file_path)
        
        # Get the data as a NumPy array
        data = img.get_fdata()
        
        # Append the 3D image data to the list
        image_list.append(data)
        
        # Print the filename and data shape
        #print(f"Loaded {filename}, shape: {data.shape}")

# Stack the 3D images along a new axis to create a 4D tensor
if image_list:
    image_tensor = np.stack(image_list, axis=0)
    #print(f"Stacked 4D tensor shape: {image_tensor.shape}")
else:
    print("No images loaded.")


X_train, X_test, y_train, y_test = train_test_split(image_tensor, y_variable, test_size=0.2, random_state=42)
y_train = np.nan_to_num(y_train, nan=0.0)
# Print the shapes of the training and testing data
print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_test shape: {y_test.shape}")


start_time = time.time()
model_list = list()  
pred_list = list()
RSE_list = list()
for i in range(2, X_train.shape[3]-2):
    sl = X_train[:, :, :, i]  
    model = TensorDecisionTreeRegressor( 
        max_depth=3, 
        min_samples_split=2, 
        split_method='variance', 
        split_rank=3,
        n_mode = 3)   
    model.sample_rate = 1
    model.fit(sl, y_train)
    #model.prune(X_val=None, y_val=None, model_type='mean')
    predictions = model.predict(X_test[:, :, :, i])
    res = mean_squared_error(predictions, y_test)/np.var(y_test)
    pred_list.append(predictions)
    model_list.append(model)
    RSE_list.append(res)

    end_time = time.time()
    print(res)
print(f"computation time : ", end_time - start_time)
#print(f"predictions with {s} samples: ", pred_list)
print(f"RSE with : ", mean_squared_error(np.mean(np.array(pred_list), axis = 0), y_test)/np.var(y_test))

y variable shape: (818,)
First 5 values of y variable: [ 3.    3.33  6.   19.33  3.67]
X_train shape: (654, 48, 48, 48)
y_train shape: (654,)
X_test shape: (164, 48, 48, 48)
y_test shape: (164,)
1.0750434279809133
1.0775019791806655
1.2439608966266356
1.1016695136231303
1.0252243781813475
1.0078110889060559
1.0691952912017273
1.0161607628576266
1.0314500087463934
1.1061532825813178
1.172809946331204
1.2078056345002424
1.0545115655051773
1.0666288953919678
1.1520233437487073
1.1453691710703686
1.2229795686022895
1.0494900023930218
1.2308249033568566
0.9971057776018203
1.0456089838085418
1.1227073454388494
1.0392585515692025
1.159731468093575
1.2472617324602884
1.1068263982292676
1.08568799458972
1.1097365670348307
1.145007066156149
1.2939614627671059
1.0389010107474719
1.1254017315591711
1.0023229870342147
1.1027473502722236
1.0534326438616577
1.1493216764474548
1.0337022286528927
1.0515782856130695
1.1601031478246537
1.2804008573038723
1.0954287304204406
1.3327939554892072
1.0088831221

In [39]:
X_train, X_test, y_train, y_test = train_test_split(image_tensor, y_variable, test_size=0.2, random_state=42)
y_train = np.nan_to_num(y_train, nan=0.0)
# Print the shapes of the training and testing data
print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_test shape: {y_test.shape}")


start_time = time.time()
model_list = list()  
pred_list = list()
RSE_list = list()
for i in range(2, X_train.shape[2]-2):
    sl = X_train[:, :, i, :]  
    model = TensorDecisionTreeRegressor( 
        max_depth=3, 
        min_samples_split=2, 
        split_method='variance', 
        split_rank=3,
        n_mode = 3)   
    model.sample_rate = 1
    model.fit(sl, y_train)
    #model.prune(X_val=None, y_val=None, model_type='mean')
    predictions = model.predict(X_test[:, :, i, :])
    res = mean_squared_error(predictions, y_test)/np.var(y_test)
    pred_list.append(predictions)
    model_list.append(model)
    RSE_list.append(res)

    end_time = time.time()
    print(res)
print(f"computation time : ", end_time - start_time)
#print(f"predictions with {s} samples: ", pred_list)
print(f"RSE with : ", mean_squared_error(np.mean(np.array(pred_list), axis = 0), y_test)/np.var(y_test))

X_train shape: (654, 48, 48, 48)
y_train shape: (654,)
X_test shape: (164, 48, 48, 48)
y_test shape: (164,)
1.025981151115912
1.072619427620394
1.0594910864948026
1.1173897948764215
1.0297471409185497
1.1133563775347188
1.2373037778439655
1.2774319263606433
1.00902804044761
1.1258362418912087
1.2135359890375377
1.1368678362723943
1.0168030483855584
1.1722301927342589
0.9895818334862657
1.1953548179394704
1.140048323286926
1.07912980532979
1.0124986963335945
1.0708049657751595
1.1134005315571434
1.1208709603317348
1.0676540302913782
1.0981072201690878
1.0936046062486144
1.0527280968112194
1.2990849972227094
1.1476651487311804
1.1320032567069145
1.0371198996062323
1.0963034323717544
1.1114380985996077
1.1165964555507353
1.2556080242651937
1.0750708436973686
1.1743704245878417
1.0463136908596609
1.205839230804664
1.1105727032614678
1.068026529649368
1.1597877621126
1.055858362582511
1.0953719276032685
1.1892441160256275
computation time :  3863.2316851615906
RSE with :  1.0095067091145924

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(image_tensor, y_variable, test_size=0.2, random_state=42)
y_train = np.nan_to_num(y_train, nan=0.0)
# Print the shapes of the training and testing data
print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_test shape: {y_test.shape}")


start_time = time.time()
model_list = list()  
pred_list = list()
RSE_list = list()
for i in range(2, X_train.shape[1]-2):
    sl = X_train[:, i, :, :]  
    model = TensorDecisionTreeRegressor( 
        max_depth=3, 
        min_samples_split=2, 
        split_method='variance', 
        split_rank=3,
        n_mode = 3)   
    model.sample_rate = 1
    model.fit(sl, y_train)
    #model.prune(X_val=None, y_val=None, model_type='mean')
    predictions = model.predict(X_test[:, i, :, :])
    res = mean_squared_error(predictions, y_test)/np.var(y_test)
    pred_list.append(predictions)
    model_list.append(model)
    RSE_list.append(res)

    end_time = time.time()
    print(res)
print(f"computation time : ", end_time - start_time)
#print(f"predictions with {s} samples: ", pred_list)
print(f"RSE with : ", mean_squared_error(np.mean(np.array(pred_list), axis = 0), y_test)/np.var(y_test))

In [44]:

start_time = time.time()
model = TensorDecisionTreeRegressor( 
        max_depth=4, 
        min_samples_split=2, 
        split_method='variance_LS', 
        split_rank=3,
        n_mode = 4)   
model.sample_rate = 0.1
X_train, X_test, y_train, y_test = train_test_split(image_tensor, y_variable, test_size=0.2, random_state=42)
y_train = np.nan_to_num(y_train, nan=0.0)
#trimmed_tensor by cutting edges
X_train = X_train[:, 3:-3, 3:-3, 3:-3]
X_test = X_test[:, 3:-3, 3:-3, 3:-3]



model.fit(X_train, y_train)
#model.prune(X_val=None, y_val=None, model_type='mean')
predictions = model.predict(X_test)
res = mean_squared_error(predictions, y_test)/np.var(y_test)


end_time = time.time()

print(f"computation time : ", end_time - start_time)
#print(f"predictions with {s} samples: ", pred_list)
print(f"RSE with : ", res)

computation time :  862.9726917743683
RSE with :  1.197412036638442


In [45]:
start_time = time.time()
model = TensorDecisionTreeRegressor( 
        max_depth=3, 
        min_samples_split=2, 
        split_method='variance', 
        split_rank=4,
        n_mode = 4)   
model.sample_rate = 1
X_train, X_test, y_train, y_test = train_test_split(image_tensor, y_variable, test_size=0.2, random_state=42)
y_train = np.nan_to_num(y_train, nan=0.0)
#trimmed_tensor by cutting edges
X_train = X_train[:, 3:-3, 3:-3, 3:-3]
X_test = X_test[:, 3:-3, 3:-3, 3:-3]



model.fit(X_train, y_train)
#model.prune(X_val=None, y_val=None, model_type='mean')
predictions = model.predict(X_test)
res = mean_squared_error(predictions, y_test)/np.var(y_test)


end_time = time.time()

print(f"computation time : ", end_time - start_time)
#print(f"predictions with {s} samples: ", pred_list)
print(f"RSE with : ", res)

computation time :  673.6525812149048
RSE with :  1.0009991928218434


In [50]:
start_time = time.time()
model = TensorDecisionTreeRegressor( 
        max_depth=3, 
        min_samples_split=2, 
        split_method='lowrank_LS', 
        split_rank=3,
        n_mode = 4)   
model.sample_rate = 0.1
X_train, X_test, y_train, y_test = train_test_split(image_tensor, y_variable, test_size=0.2, random_state=42)
y_train = np.nan_to_num(y_train, nan=0.0)
#trimmed_tensor by cutting edges
X_train = X_train[:, 6:-6, 6:-6, 6:-6]
X_test = X_test[:, 6:-6, 6:-6, 6:-6]



model.fit(X_train, y_train)
#model.prune(X_val=None, y_val=None, model_type='mean')
predictions = model.predict(X_test)
res = mean_squared_error(predictions, y_test)/np.var(y_test)


end_time = time.time()

print(f"computation time : ", end_time - start_time)
#print(f"predictions with {s} samples: ", pred_list)
print(f"RSE with : ", res)

KeyboardInterrupt: 

In [51]:
print(i)

5


In [93]:
np.random.seed(42) # for reproducibility
Xq = np.random.rand(250, 7, 7,7)

# def test_func_tensor(X):
#  y = 10 * np.sin(np.pi * X[:, 1,0, 1] * X[:, 1,1, 0]) +\
#  20 * (X[:, 3,2, 0] - 0.5) ** 2 +\
#  10 * X[:, 2,0, 1] +\
#  30 * X[:, 0, 1,1] +\
#  0.1 * np.random.randn(X.shape[0])
#  return y
def test_func_tensor(X):
    y = 10 * np.sin(np.pi * X[:, 1, 4, 3] * X[:, 1, 2, 3]) + 0.1 * np.random.randn(X.shape[0])
    return y


Y = test_func_tensor(Xq)

print(Y)
X_train, X_test = train_test_split(Xq, test_size=0.2)
y_train, y_test = train_test_split(Y, test_size=0.2)
if X_train.size == 0 or X_test.size == 0:
    raise ValueError("Training or test set is empty. Ensure enough data samples.")

# Simulate some target data
#y_train = 10 * np.sin(np.pi * X_train[:, 1, 4, 3] * X_train[:, 1, 2, 3]) + 0.1 * np.random.randn(X_train.shape[0])
# Ensure y_train has the same number of samples as X_train
#y_train = 10 * np.sin(np.pi * X_train[:, 1, :, :] * X_train[:, 2, :, :]).sum(axis=(1, 2)) + 0.1 * np.random.randn(X_train.shape[0])

#y_test = 10 * np.sin(np.pi * X_test[:, 1, 4, 3] * X_test[:, 1, 2, 3]) + 0.1 * np.random.randn(X_test.shape[0])
#y_test = 10 * np.sin(np.pi * X_test[:, 1, :, :] * X_test[:, 2, :, :]).sum(axis=(1, 2)) + 0.1 * np.random.randn(X_train.shape[0])

start_time = time.time()

model = TensorDecisionTreeRegressor(
    max_depth=3,
    min_samples_split=2,
    split_method='variance',
    split_rank=3,
    CP_reg_rank=3,
    Tucker_reg_rank=3,
    n_mode=3
)

model.fit(X_train, y_train)
model.prune(alpha = 0.)
predictions = model.predict(X_test)
res = mean_squared_error(predictions, y_test) / np.var(y_test)

end_time = time.time()
computation_time = end_time - start_time
print("computation time: ", computation_time)
print("relative error: ", res)


[ 3.63675516e+00  1.37485628e+00  9.94031251e+00  6.46337706e-01
  5.26415485e+00  2.51959606e+00  5.57131606e+00  1.04753916e+00
  2.57902417e+00  1.23768706e+00  7.97213394e+00  8.95099073e+00
  6.47103951e-01  1.18580599e+00  9.85512726e+00  4.19061995e-01
  8.12054799e+00  8.30843815e+00  9.07499844e+00  5.68095096e-01
  8.62455590e+00  6.39175014e+00  5.87335593e+00  1.00227068e+01
  9.67641198e-02  5.80315678e+00  5.85424467e-02  3.36577289e+00
  7.04283987e+00  8.00529489e+00  7.86410501e+00  7.89301444e+00
  9.84231304e+00  7.51366747e+00  1.40096107e+00  3.72202221e+00
  1.25935732e+00  9.89493220e+00  3.82484419e+00  2.56605119e+00
  9.24158230e+00  3.90806309e+00  1.72751717e-01  9.10951428e+00
  5.78940907e+00  1.81334126e+00  7.32511733e-03  8.23573930e+00
  9.94312736e+00  9.92867416e+00  2.55302102e+00  3.21943657e+00
  8.67134503e+00  6.10511557e+00  2.31930152e+00  2.76560171e+00
  8.87897923e+00  9.10920953e-01  9.41809087e+00  9.61025567e-01
  1.45897122e+00  1.14219

In [78]:
model.print_tree()

  if X[:, 0 , 1 , 0 ] <=  0.5077583878959304
   if X[:, 0 , 1 , 1 ] <=  0.4901248551971618
     if X[:, 0 , 2 , 1 ] <=  0.49908100502201574
         has  0  child nodes, and  102  samples.
     else: # if X[:, 0 , 2 , 1 ] >  0.49908100502201574
         has  0  child nodes, and  103  samples.
   else: # if X[:, 0 , 1 , 1 ] >  0.4901248551971618
     if X[:, 1 , 3 , 0 ] <=  0.5314321898262089
         has  0  child nodes, and  91  samples.
     else: # if X[:, 1 , 3 , 0 ] >  0.5314321898262089
         has  0  child nodes, and  95  samples.
  else: # if X[:, 0 , 1 , 0 ] >  0.5077583878959304
   if X[:, 1 , 2 , 0 ] <=  0.48389719849852514
     if X[:, 2 , 0 , 0 ] <=  0.47033080386803017
         has  0  child nodes, and  100  samples.
     else: # if X[:, 2 , 0 , 0 ] >  0.47033080386803017
         has  0  child nodes, and  102  samples.
   else: # if X[:, 1 , 2 , 0 ] >  0.48389719849852514
     if X[:, 1 , 2 , 1 ] <=  0.4996288434111002
         has  0  child nodes, and  99  samples.
  

In [94]:
# sliced 3D real image
import warnings
warnings.filterwarnings("ignore")


import numpy as np
from concurrent.futures import ProcessPoolExecutor
import time
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
import tensorly as tl

#Debugging import
import importlib
var = 'TensorDecisionTreeRegressorP' #the published version of code
package = importlib.import_module(var)
for name, value in package.__dict__.items():
    if not name.startswith("__"):
        globals()[name] = value

from TensorDecisionTreeRegressorP import *

import os
import nibabel as nib
import numpy as np
import matplotlib as plt
import pandas as pd
from sklearn.model_selection import train_test_split

# File path to the CSV file
csv_file = '/Users/zc56/Documents/CommenDesktop/RICE/MyProject/Bayes_Tensor_Tree/3D-images/ADNIData.csv'
#csv_file = '/home/zc56/Bayes_Tensor_Tree/3D-images/ADNIData.csv'
# Load the CSV file into a pandas DataFrame
df = pd.read_csv(csv_file)

# Extract the 'ADAS11' column as the y variable
y_variable = df['ADAS11'].values  # Convert to NumPy array if needed

# Print the shape and first few values of the y variable
print(f"y variable shape: {y_variable.shape}")
print(f"First 5 values of y variable: {y_variable[:5]}")





directory = '/Users/zc56/Documents/CommenDesktop/RICE/MyProject/Bayes_Tensor_Tree/3D-images/3D-Images/bl'
#directory = '/home/zc56/Bayes_Tensor_Tree/3D-images/3D-Images/bl'
# Initialize a list to hold 3D images
# Initialize a list to hold 3D images
image_list = []

# Loop over all files in the directory
for filename in os.listdir(directory):
    if filename.endswith('.nii.gz'):
        file_path = os.path.join(directory, filename)
        
        # Load the NIfTI file
        img = nib.load(file_path)
        
        # Get the data as a NumPy array
        data = img.get_fdata()
        
        # Append the 3D image data to the list
        image_list.append(data)
        
        # Print the filename and data shape
        #print(f"Loaded {filename}, shape: {data.shape}")

# Stack the 3D images along a new axis to create a 4D tensor
if image_list:
    image_tensor = np.stack(image_list, axis=0)
    #print(f"Stacked 4D tensor shape: {image_tensor.shape}")
else:
    print("No images loaded.")


X_train, X_test, y_train, y_test = train_test_split(image_tensor, y_variable, test_size=0.2, random_state=42)
y_train = np.nan_to_num(y_train, nan=0.0)
# Print the shapes of the training and testing data
print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_test shape: {y_test.shape}")


start_time = time.time()
model_list = list()  
pred_list = list()
RSE_list = list()
for i in range(2, X_train.shape[3]-2):
    sl = X_train[:, :, :, i]  
    model = TensorDecisionTreeRegressor( 
        max_depth=3, 
        min_samples_split=2, 
        split_method='lowrank_LS', 
        split_rank=3,
        n_mode = 3)   
    model.sample_rate = 0.001
    model.fit(sl, y_train)
    #model.prune(X_val=None, y_val=None, model_type='mean')
    predictions = model.predict(X_test[:, :, :, i])
    res = mean_squared_error(predictions, y_test)/np.var(y_test)
    pred_list.append(predictions)
    model_list.append(model)
    RSE_list.append(res)

    end_time = time.time()
    print(res)
print(f"computation time : ", end_time - start_time)
#print(f"predictions with {s} samples: ", pred_list)
print(f"RSE with : ", mean_squared_error(np.mean(np.array(pred_list), axis = 0), y_test)/np.var(y_test))

y variable shape: (818,)
First 5 values of y variable: [ 3.    3.33  6.   19.33  3.67]
X_train shape: (654, 48, 48, 48)
y_train shape: (654,)
X_test shape: (164, 48, 48, 48)
y_test shape: (164,)
1.033433867581106
1.0181178762008662
1.023449417895059
1.0027799775539734
1.0104495696225353
1.0058323161063722
1.0008201144820439
1.0068122141644562
1.0063492661247966
1.020591085100601
1.0082796892103647
1.044712060650201
None-->X (4, 48, 48) [[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 

ValueError: cannot reshape array of size 0 into shape (0,48,newaxis)

In [97]:
# sliced 3D real image
import warnings
warnings.filterwarnings("ignore")


import numpy as np
from concurrent.futures import ProcessPoolExecutor
import time
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
import tensorly as tl

#Debugging import
import importlib
var = 'TensorDecisionTreeRegressor' #the published version of code
package = importlib.import_module(var)
for name, value in package.__dict__.items():
    if not name.startswith("__"):
        globals()[name] = value

from TensorDecisionTreeRegressorP import *

import os
import nibabel as nib
import numpy as np
import matplotlib as plt
import pandas as pd
from sklearn.model_selection import train_test_split

# File path to the CSV file
csv_file = '/Users/zc56/Documents/CommenDesktop/RICE/MyProject/Bayes_Tensor_Tree/3D-images/ADNIData.csv'
#csv_file = '/home/zc56/Bayes_Tensor_Tree/3D-images/ADNIData.csv'
# Load the CSV file into a pandas DataFrame
df = pd.read_csv(csv_file)

# Extract the 'ADAS11' column as the y variable
y_variable = df['ADAS11'].values  # Convert to NumPy array if needed

# Print the shape and first few values of the y variable
print(f"y variable shape: {y_variable.shape}")
print(f"First 5 values of y variable: {y_variable[:5]}")





directory = '/Users/zc56/Documents/CommenDesktop/RICE/MyProject/Bayes_Tensor_Tree/3D-images/3D-Images/bl'
#directory = '/home/zc56/Bayes_Tensor_Tree/3D-images/3D-Images/bl'
# Initialize a list to hold 3D images
# Initialize a list to hold 3D images
image_list = []

# Loop over all files in the directory
for filename in os.listdir(directory):
    if filename.endswith('.nii.gz'):
        file_path = os.path.join(directory, filename)
        
        # Load the NIfTI file
        img = nib.load(file_path)
        
        # Get the data as a NumPy array
        data = img.get_fdata()
        
        # Append the 3D image data to the list
        image_list.append(data)
        
        # Print the filename and data shape
        #print(f"Loaded {filename}, shape: {data.shape}")

# Stack the 3D images along a new axis to create a 4D tensor
if image_list:
    image_tensor = np.stack(image_list, axis=0)
    #print(f"Stacked 4D tensor shape: {image_tensor.shape}")
else:
    print("No images loaded.")


X_train, X_test, y_train, y_test = train_test_split(image_tensor, y_variable, test_size=0.2, random_state=42)
y_train = np.nan_to_num(y_train, nan=0.0)
# Print the shapes of the training and testing data
print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_test shape: {y_test.shape}")


start_time = time.time()
model_list = list()  
pred_list = list()
RSE_list = list()
for i in range(2, X_train.shape[3]-2):
    sl = X_train[:, :, :, i]  
    model = TensorDecisionTreeRegressor( 
        max_depth=3, 
        min_samples_split=2, 
        split_method='variance_BB', 
        split_rank=3,
        n_mode = 3)   
    model.sample_rate = 0.001
    #model.use_mean_as_threshold = True 
    model.fit(sl, y_train)
    #model.prune(X_val=None, y_val=None, model_type='mean')
    predictions = model.predict(X_test[:, :, :, i])
    res = mean_squared_error(predictions, y_test)/np.var(y_test)
    pred_list.append(predictions)
    model_list.append(model)
    RSE_list.append(res)

    end_time = time.time()
    print(res)
print(f"computation time : ", end_time - start_time)
#print(f"predictions with {s} samples: ", pred_list)
print(f"RSE with : ", mean_squared_error(np.mean(np.array(pred_list), axis = 0), y_test)/np.var(y_test))

ModuleNotFoundError: No module named 'TensorDecisionTreeRegressor'